// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Infra.Data.Context;

#nullable disable

namespace WebAPI.Infra.Migrations
{
    [DbContext(typeof(WebAPIContext))]
    [Migration("20240717232758_alterar_ordem_colunas_tbProfileOperation")]
    partial class alterar_ordem_colunas_tbProfileOperation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Domain.Entities.ArchiveType", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 37, DateTimeKind.Unspecified).AddTicks(7933))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("ArchiveType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            Description = "Word",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            Description = "Excel",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            Description = "Pdf",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            Description = "Txt",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            Description = "Jpg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            Description = "Word",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            Description = "Png",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Audit", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Action_Name");

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 36, DateTimeKind.Unspecified).AddTicks(9040))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<string>("KeyValues")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Key_Values");

                    b.Property<string>("NewValues")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("New_Values");

                    b.Property<string>("OldValues")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Old_Values");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Table_Name");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.City", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 37, DateTimeKind.Unspecified).AddTicks(5537))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<long?>("IBGE")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("bigint")
                        .HasColumnName("Ibge");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("City");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Client", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 37, DateTimeKind.Unspecified).AddTicks(2558))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.ControlPanel.Area", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 38, DateTimeKind.Unspecified).AddTicks(4802))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("HierarchyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HierarchyLevel");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("Order");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Administrador Dev",
                            HierarchyLevel = "Development",
                            IsActive = true,
                            Order = 0
                        },
                        new
                        {
                            Id = 2L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Administrador Sistema",
                            HierarchyLevel = "Principal",
                            IsActive = true,
                            Order = 0
                        },
                        new
                        {
                            Id = 3L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Setor Operacional",
                            HierarchyLevel = "Areas",
                            IsActive = true,
                            Order = 0
                        },
                        new
                        {
                            Id = 4L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Setor Financeiro",
                            HierarchyLevel = "Areas",
                            IsActive = true,
                            Order = 1
                        },
                        new
                        {
                            Id = 5L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Setor Marketing",
                            HierarchyLevel = "Areas",
                            IsActive = true,
                            Order = 2
                        },
                        new
                        {
                            Id = 6L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Setor Relações Humanas",
                            HierarchyLevel = "Areas",
                            IsActive = true,
                            Order = 3
                        });
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.ControlPanel.Employee", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<string>("CelPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CelPhone");

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 38, DateTimeKind.Unspecified).AddTicks(7289))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Email");

                    b.Property<long>("IdProfile")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Name");

                    b.Property<string>("TelPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TelPhone");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("IdProfile");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CelPhone = "12999991234",
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Email = "xpto@gmail.com",
                            IdProfile = 1L,
                            IdUser = 1L,
                            IsActive = true,
                            Name = "Administrador Desenvolvedor",
                            TelPhone = "1233336789"
                        });
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.ControlPanel.Operation", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 37, DateTimeKind.Unspecified).AddTicks(1326))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Operation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Auditoria",
                            IsActive = true,
                            Order = 1
                        },
                        new
                        {
                            Id = 2L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Logs",
                            IsActive = true,
                            Order = 2
                        },
                        new
                        {
                            Id = 3L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Area",
                            IsActive = true,
                            Order = 3
                        },
                        new
                        {
                            Id = 4L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Operação",
                            IsActive = true,
                            Order = 4
                        },
                        new
                        {
                            Id = 5L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Perfil",
                            IsActive = true,
                            Order = 5
                        },
                        new
                        {
                            Id = 6L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Funcionario",
                            IsActive = true,
                            Order = 6
                        },
                        new
                        {
                            Id = 7L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Usuario",
                            IsActive = true,
                            Order = 7
                        });
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.ControlPanel.Profile", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 35, DateTimeKind.Unspecified).AddTicks(9069))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.ToTable("Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Perfil Desenvolvedor",
                            IdArea = 1L,
                            IsActive = true
                        },
                        new
                        {
                            Id = 2L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Perfil Administrador",
                            IdArea = 2L,
                            IsActive = true
                        },
                        new
                        {
                            Id = 3L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Perfil Manager Operacional",
                            IdArea = 3L,
                            IsActive = true
                        },
                        new
                        {
                            Id = 4L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            Description = "Perfil Manager Financeiro",
                            IdArea = 4L,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.ControlPanel.ProfileOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IdProfile")
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Profile")
                        .HasColumnOrder(1);

                    b.Property<long>("IdOperation")
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Operation")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsEnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsEnable")
                        .HasColumnOrder(4);

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("Order")
                        .HasColumnOrder(5);

                    b.Property<string>("RoleTag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RoleTag")
                        .HasColumnOrder(3);

                    b.HasKey("Id", "IdProfile", "IdOperation");

                    b.HasIndex("IdOperation");

                    b.HasIndex("IdProfile");

                    b.HasIndex("Id", "IdProfile", "IdOperation")
                        .IsUnique();

                    b.ToTable("ProfileOperations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IdProfile = 1L,
                            IdOperation = 1L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 2L,
                            IdProfile = 1L,
                            IdOperation = 1L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 3L,
                            IdProfile = 1L,
                            IdOperation = 1L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 4L,
                            IdProfile = 1L,
                            IdOperation = 1L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 5L,
                            IdProfile = 1L,
                            IdOperation = 2L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 6L,
                            IdProfile = 1L,
                            IdOperation = 2L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 7L,
                            IdProfile = 1L,
                            IdOperation = 2L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 8L,
                            IdProfile = 1L,
                            IdOperation = 2L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 9L,
                            IdProfile = 1L,
                            IdOperation = 3L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 10L,
                            IdProfile = 1L,
                            IdOperation = 3L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 11L,
                            IdProfile = 1L,
                            IdOperation = 3L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 12L,
                            IdProfile = 1L,
                            IdOperation = 3L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 13L,
                            IdProfile = 1L,
                            IdOperation = 4L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 14L,
                            IdProfile = 1L,
                            IdOperation = 4L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 15L,
                            IdProfile = 1L,
                            IdOperation = 4L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 16L,
                            IdProfile = 1L,
                            IdOperation = 4L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 17L,
                            IdProfile = 1L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 18L,
                            IdProfile = 1L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 19L,
                            IdProfile = 1L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 2L,
                            IdProfile = 1L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 21L,
                            IdProfile = 1L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 22L,
                            IdProfile = 1L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 23L,
                            IdProfile = 1L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 24L,
                            IdProfile = 1L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 25L,
                            IdProfile = 1L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 26L,
                            IdProfile = 1L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 27L,
                            IdProfile = 1L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 28L,
                            IdProfile = 1L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 29L,
                            IdProfile = 2L,
                            IdOperation = 2L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 30L,
                            IdProfile = 2L,
                            IdOperation = 2L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 31L,
                            IdProfile = 2L,
                            IdOperation = 2L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 32L,
                            IdProfile = 2L,
                            IdOperation = 2L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 33L,
                            IdProfile = 2L,
                            IdOperation = 3L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 34L,
                            IdProfile = 2L,
                            IdOperation = 3L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 35L,
                            IdProfile = 2L,
                            IdOperation = 3L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 36L,
                            IdProfile = 2L,
                            IdOperation = 3L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 37L,
                            IdProfile = 2L,
                            IdOperation = 4L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 38L,
                            IdProfile = 2L,
                            IdOperation = 4L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 39L,
                            IdProfile = 2L,
                            IdOperation = 4L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 40L,
                            IdProfile = 2L,
                            IdOperation = 4L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 41L,
                            IdProfile = 2L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 42L,
                            IdProfile = 2L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 43L,
                            IdProfile = 2L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 44L,
                            IdProfile = 2L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 45L,
                            IdProfile = 2L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 46L,
                            IdProfile = 2L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 47L,
                            IdProfile = 2L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 48L,
                            IdProfile = 2L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 49L,
                            IdProfile = 2L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 50L,
                            IdProfile = 2L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 51L,
                            IdProfile = 2L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 52L,
                            IdProfile = 2L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 53L,
                            IdProfile = 3L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 54L,
                            IdProfile = 3L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 55L,
                            IdProfile = 3L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 56L,
                            IdProfile = 3L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 57L,
                            IdProfile = 3L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 58L,
                            IdProfile = 3L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 59L,
                            IdProfile = 3L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 60L,
                            IdProfile = 3L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 61L,
                            IdProfile = 3L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 62L,
                            IdProfile = 3L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 63L,
                            IdProfile = 3L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 64L,
                            IdProfile = 3L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 65L,
                            IdProfile = 4L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 66L,
                            IdProfile = 4L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 67L,
                            IdProfile = 4L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 68L,
                            IdProfile = 4L,
                            IdOperation = 5L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 69L,
                            IdProfile = 4L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 70L,
                            IdProfile = 4L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 71L,
                            IdProfile = 4L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 72L,
                            IdProfile = 4L,
                            IdOperation = 6L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 73L,
                            IdProfile = 4L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 0,
                            RoleTag = "ROLE_NEW"
                        },
                        new
                        {
                            Id = 74L,
                            IdProfile = 4L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 1,
                            RoleTag = "ROLE_EDIT"
                        },
                        new
                        {
                            Id = 75L,
                            IdProfile = 4L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 2,
                            RoleTag = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 76L,
                            IdProfile = 4L,
                            IdOperation = 7L,
                            IsEnable = true,
                            Order = 3,
                            RoleTag = "ROLE_VIEW"
                        });
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.ControlPanel.User", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 35, DateTimeKind.Unspecified).AddTicks(7079))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<bool>("HasTwoFactoryValidation")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InicioValidade")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("InicioValidade");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsAuthenticated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Is_Authenticated");

                    b.Property<string>("LastPassword")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Last_Password");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.Property<DateTime>("TerminoValidade")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("TerminoValidade");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UsersHistory");
                                ttb
                                    .HasPeriodStart("InicioValidade")
                                    .HasColumnName("InicioValidade");
                                ttb
                                    .HasPeriodEnd("TerminoValidade")
                                    .HasColumnName("TerminoValidade");
                            }));

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 39, DateTimeKind.Unspecified).AddTicks(515),
                            HasTwoFactoryValidation = false,
                            IsActive = true,
                            IsAuthenticated = true,
                            LastPassword = "",
                            Login = "admin@DefaultAPI.com.br",
                            Password = "AQAQJwAAFSnSFRtk18A0UGvwJBAJvzG4QYLH+vJwleaNzhWuqVw="
                        });
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.EmailDisplay", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Body");

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 38, DateTimeKind.Unspecified).AddTicks(1197))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<long>("EmailTemplateId")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasAttachment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("HasAttachment");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("Priority");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Subject");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("EmailDisplay", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Body = "Olá, {0}<br>Seja bem vindo ao <b>{1}</b><br> Utilize a senha <b>1234</b> para acessar o sistema e usufrua de todas as ferramentas disponíveis.<br>",
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            EmailTemplateId = 1L,
                            HasAttachment = false,
                            IsActive = true,
                            Priority = 1,
                            Subject = "Bem vindo ao sistema {0}",
                            Title = "Boas vindas"
                        },
                        new
                        {
                            Id = 2L,
                            Body = "<center>Olá, {0}</center><center>Conforme sua solicitação enviamos este email para que você possa concluir sua solicitação de esqueci a senha. Clique no botão abaixo.</center><br> ",
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            EmailTemplateId = 1L,
                            HasAttachment = false,
                            IsActive = true,
                            Priority = 1,
                            Subject = "{0} - Esqueci a senha",
                            Title = "Esqueci a senha"
                        },
                        new
                        {
                            Id = 3L,
                            Body = "<center>Olá, {0}</center><center>Conforme sua solicitação enviamos este email para que você possa concluir sua solicitação de troca de senha. Clique no botão abaixo.</center><br> ",
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            EmailTemplateId = 1L,
                            HasAttachment = false,
                            IsActive = true,
                            Priority = 1,
                            Subject = "{0} - Solicitação de troca de senha",
                            Title = "Troca de senha"
                        },
                        new
                        {
                            Id = 4L,
                            Body = "<center>Olá, {0}</center><center>Quero reporta-lo que a sua confirmação de senha foi realizada com sucesso no periodo das 17/07/2024 - 20:27</center><br> ",
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            EmailTemplateId = 1L,
                            HasAttachment = false,
                            IsActive = true,
                            Priority = 1,
                            Subject = "{0} - Confirmação de senha",
                            Title = "Confirmação de senha"
                        },
                        new
                        {
                            Id = 5L,
                            Body = "",
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            EmailTemplateId = 1L,
                            HasAttachment = false,
                            IsActive = true,
                            Priority = 1,
                            Subject = "{0} - Relatório",
                            Title = "Relatório"
                        });
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 37, DateTimeKind.Unspecified).AddTicks(9324))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("EmailTemplate", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            Description = "WebAPI",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.EmailType", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 38, DateTimeKind.Unspecified).AddTicks(3400))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<string>("SmtpConfig")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("SmtpConfig");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("EmailType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            Description = "Gmail",
                            IsActive = true,
                            SmtpConfig = "smtp.gmail.com"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            Description = "Outlook",
                            IsActive = true,
                            SmtpConfig = "smtp.office365.com"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 27, 58, 46, DateTimeKind.Unspecified).AddTicks(5394),
                            Description = "Hotmail",
                            IsActive = true,
                            SmtpConfig = "smtp.live.com"
                        });
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Class");

                    b.Property<string>("MessageError")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Message_Error");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Method");

                    b.Property<string>("Object")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Object");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Notification", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 37, DateTimeKind.Unspecified).AddTicks(4661))
                        .HasColumnName("Created_Time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active");

                    b.HasKey("Id");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Region", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 36, DateTimeKind.Unspecified).AddTicks(7657))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Initials");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.States", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 36, DateTimeKind.Unspecified).AddTicks(2765))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Initials");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("States", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.ValueObject.AddressData", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Cep");

                    b.Property<string>("Complement")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Complement");

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 7, 17, 20, 27, 58, 36, DateTimeKind.Unspecified).AddTicks(4794))
                        .HasColumnName("Created_Time")
                        .HasColumnOrder(1);

                    b.Property<string>("Ddd")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ddd");

                    b.Property<string>("District")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("District");

                    b.Property<string>("Gia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Gia");

                    b.Property<string>("Ibge")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ibge");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active")
                        .HasColumnOrder(3);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Siafi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Siafi");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Street")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Address");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Uf");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_Time")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Ceps", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.City", b =>
                {
                    b.HasOne("WebAPI.Domain.Entities.States", "States")
                        .WithMany("City")
                        .HasForeignKey("StateId")
                        .IsRequired();

                    b.Navigation("States");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Client", b =>
                {
                    b.OwnsOne("WebAPI.Domain.Entities.Address", "ClientAddress", b1 =>
                        {
                            b1.Property<long>("ClientId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Cep")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Cep");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("City");

                            b1.HasKey("ClientId");

                            b1.ToTable("ClientAddress", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.OwnsOne("WebAPI.Domain.Entities.Document", "ClientDocument", b1 =>
                        {
                            b1.Property<long>("ClientId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Cpf")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Cpf");

                            b1.Property<string>("Rg")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Rg");

                            b1.HasKey("ClientId");

                            b1.ToTable("ClientDocument", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("ClientAddress");

                    b.Navigation("ClientDocument");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.ControlPanel.Employee", b =>
                {
                    b.HasOne("WebAPI.Domain.Entities.ControlPanel.Profile", "Profile")
                        .WithMany("Employees")
                        .HasForeignKey("IdProfile")
                        .IsRequired();

                    b.HasOne("WebAPI.Domain.Entities.ControlPanel.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("WebAPI.Domain.Entities.ControlPanel.Employee", "IdUser")
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.ControlPanel.Profile", b =>
                {
                    b.HasOne("WebAPI.Domain.Entities.ControlPanel.Area", "Area")
                        .WithMany("Profiles")
                        .HasForeignKey("IdArea")
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.ControlPanel.ProfileOperation", b =>
                {
                    b.HasOne("WebAPI.Domain.Entities.ControlPanel.Operation", "Operation")
                        .WithMany("ProfileOperations")
                        .HasForeignKey("IdOperation")
                        .IsRequired();

                    b.HasOne("WebAPI.Domain.Entities.ControlPanel.Profile", "Profile")
                        .WithMany("ProfileOperations")
                        .HasForeignKey("IdProfile")
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.EmailDisplay", b =>
                {
                    b.HasOne("WebAPI.Domain.Entities.EmailTemplate", "EmailTemplates")
                        .WithMany("EmailDisplays")
                        .HasForeignKey("EmailTemplateId")
                        .IsRequired();

                    b.Navigation("EmailTemplates");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.States", b =>
                {
                    b.HasOne("WebAPI.Domain.Entities.Region", "Region")
                        .WithMany("States")
                        .HasForeignKey("RegionId")
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("WebAPI.Domain.ValueObject.AddressData", b =>
                {
                    b.HasOne("WebAPI.Domain.Entities.States", "State")
                        .WithMany("Ceps")
                        .HasForeignKey("StateId")
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.ControlPanel.Area", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.ControlPanel.Operation", b =>
                {
                    b.Navigation("ProfileOperations");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.ControlPanel.Profile", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("ProfileOperations");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.ControlPanel.User", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.EmailTemplate", b =>
                {
                    b.Navigation("EmailDisplays");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Region", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.States", b =>
                {
                    b.Navigation("Ceps");

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
